# Generated by Django 3.2 on 2022-08-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20220810_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalnotification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'comment'), ('bookmark', 'bookmark'), ('like', 'like'), ('mentioned', 'mentioned')], max_length=15, null=True),
        ),
    ]
