# Generated by Django 3.2 on 2022-08-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_post_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('is_open', 'is_open'), ('is_closed', 'is_closed')], default='is_open', max_length=10, null=True),
        ),
    ]
