# Generated by Django 3.2 on 2022-08-10 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_post_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postbookmark',
            old_name='created',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='created',
            new_name='created_on',
        ),
    ]
