# Generated by Django 3.2 on 2022-08-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20220815_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.CharField(blank=True, choices=[('is_open', 'is_open'), ('is_closed', 'is_closed')], default='is_open', max_length=10, null=True),
        ),
    ]
