# Generated by Django 3.2 on 2022-08-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('manager', 'manager'), ('worker', 'worker'), ('admin', 'admin')], default='worker', max_length=10, null=True),
        ),
    ]
