# Generated by Django 3.2 on 2022-08-06 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', 'comment'), ('bookmark', 'bookmark'), ('assign', 'assign'), ('mentioned', 'mentioned')], max_length=15, null=True)),
                ('context', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('read_status', models.BooleanField(default=False)),
                ('notification_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_notification_by', to=settings.AUTH_USER_MODEL)),
                ('notification_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_notification_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
