# Generated by Django 3.2 on 2022-08-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('notification', '0002_normalnotification_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalnotification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentor', to='comments.comment'),
        ),
    ]
