# Generated by Django 3.2 on 2022-08-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20220810_0543'),
        ('notification', '0003_alter_normalnotification_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalnotification',
            name='bookmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarker', to='task.postbookmark'),
        ),
        migrations.AddField(
            model_name='normalnotification',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='task.postlike'),
        ),
    ]
