# Generated by Django 3.2 on 2022-08-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
        ('notification', '0005_alter_normalnotification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalnotification',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_answer', to='answer.answer'),
        ),
        migrations.AddField(
            model_name='normalnotification',
            name='answer_accept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_answer_accept', to='answer.answeraccept'),
        ),
        migrations.AlterField(
            model_name='normalnotification',
            name='notification_type',
            field=models.CharField(choices=[('comment', 'comment'), ('bookmark', 'bookmark'), ('like', 'like'), ('mentioned', 'mentioned'), ('answer', 'answer')], max_length=15, null=True),
        ),
    ]
